### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by raviolli77** [raviolli77/practice_DS_project_repo#1]
- [x] create a task list 
- [x] create sample scripts 
- [ ] have peeps review and edit
- [ ] check for spelling errors
